version : "3.8"

services:
  postgres:
    image: postgres 
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: amit
      POSTGRES_DB: amitdb
      POSTGRES_PASSWORD: amit123
      
  redis:
    image: redis
    ports:
      - "6379:6379"